# Generated by Django 5.2.2 on 2025-06-09 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
        ('restaurant', '0002_alter_fooditem_categry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=355)),
                ('address_type', models.CharField(max_length=255)),
                ('landmark', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'db_table': 'customer_address',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('amnt', models.FloatField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.fooditem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.store')),
            ],
            options={
                'verbose_name': 'cart',
                'verbose_name_plural': 'carts',
                'db_table': 'customer_cart',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CartBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_amnt', models.FloatField(blank=True, default=0, null=True)),
                ('delivery_charge', models.FloatField(default=0)),
                ('coupen_code', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.address')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'verbose_name': 'cart bill',
                'verbose_name_plural': 'cart bills',
                'db_table': 'customer_cart_bill',
                'ordering': ['-id'],
            },
        ),
    ]
