# Generated by Django 5.2.2 on 2025-06-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_address_customer_alter_cart_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='appartment',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
