# Generated by Django 5.2.2 on 2025-06-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_address_appartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
