# Generated by Django 5.2.2 on 2025-06-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartbill',
            name='address',
        ),
    ]
