# Generated by Django 5.2.2 on 2025-06-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_remove_cartbill_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Prepairing', 'Prepairing'), ('Shiped', 'Shiped'), ('Delivered', 'Delivered')], max_length=255),
        ),
    ]
