# Generated by Django 5.2.2 on 2025-06-17 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_order_delivery_charge_alter_order_status'),
        ('restaurant', '0002_alter_fooditem_categry'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.store'),
        ),
    ]
