# Generated by Django 5.2.2 on 2025-06-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_order_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Prepairing', 'Prepairing'), ('Shiped', 'Shiped'), ('Delivered', 'Delivered')], max_length=255),
        ),
    ]
