# Generated by Django 5.2.2 on 2025-06-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PL', 'PL'), ('AC', 'AC'), ('SH', 'SH'), ('DI', 'DI'), ('CA', 'CA'), ('CO', 'CO')], max_length=255),
        ),
    ]
