# Generated by Django 5.2.4 on 2025-08-20 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_order_delivery_boy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
