# Generated by Django 5.2.4 on 2025-08-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_alter_order_options_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('ACCEPTED', 'Accepted'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('COMPLETED', 'Delivered')], default='PLACED', max_length=20),
        ),
    ]
