# Generated by Django 5.2.2 on 2025-06-09 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='categry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fooditem', to='restaurant.foodcategory'),
        ),
    ]
