# Generated by Django 5.2.4 on 2025-08-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_store_email_store_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='category',
        ),
        migrations.AddField(
            model_name='store',
            name='categories',
            field=models.ManyToManyField(related_name='stores', to='restaurant.storecategory'),
        ),
    ]
