# Generated by Django 5.2.4 on 2025-08-19 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_foodcategory_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.store'),
        ),
    ]
