# Generated by Django 5.2.4 on 2025-08-20 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_foodcategory_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreManager',
        ),
    ]
