# Generated by Django 5.2.4 on 2025-08-29 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_delete_storemanager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ['id'], 'verbose_name': 'food item', 'verbose_name_plural': 'food items'},
        ),
    ]
