# Generated by Django 5.2.4 on 2025-08-29 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_fooditem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'ordering': ['id'], 'verbose_name': 'food category', 'verbose_name_plural': 'food categories'},
        ),
    ]
